import { randomBytes } from "node:crypto";
import { readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline";
import { Writable } from "node:stream";
import mysql from "mysql2/promise";

const backendDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(backendDirectory, ".env");
const schemaPath = path.join(backendDirectory, "database", "schema.sql");
const seedPath = path.join(backendDirectory, "database", "seed.sql");

function promptForHiddenInput(prompt) {
  if (!process.stdin.isTTY) {
    throw new Error(
      "Database setup needs an interactive terminal. Run `npm run db:setup` directly in the backend folder.",
    );
  }

  let muted = false;
  const hiddenOutput = new Writable({
    write(chunk, encoding, callback) {
      if (!muted) {
        process.stdout.write(chunk, encoding);
      }
      callback();
    },
  });

  const terminal = createInterface({
    input: process.stdin,
    output: hiddenOutput,
    terminal: true,
  });

  return new Promise((resolve) => {
    terminal.question(prompt, (answer) => {
      terminal.close();
      process.stdout.write("\n");
      resolve(answer);
    });
    muted = true;
  });
}

function parseEnv(source) {
  return Object.fromEntries(
    source
      .split(/\r?\n/)
      .filter((line) => line && !line.trimStart().startsWith("#") && line.includes("="))
      .map((line) => {
        const separator = line.indexOf("=");
        return [line.slice(0, separator).trim(), line.slice(separator + 1).trim()];
      }),
  );
}

async function readCurrentEnv() {
  try {
    return parseEnv(await readFile(envPath, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return {};
    throw error;
  }
}

async function saveAppEnvironment({ appPassword }) {
  const current = await readCurrentEnv();
  const jwtSecret =
    current.JWT_SECRET && !current.JWT_SECRET.startsWith("replace_")
      ? current.JWT_SECRET
      : randomBytes(48).toString("hex");

  const env = [
    "# Generated by `npm run db:setup`. This file is ignored by Git.",
    `PORT=${current.PORT ?? "4000"}`,
    `CLIENT_ORIGIN=${current.CLIENT_ORIGIN ?? "http://localhost:3000"}`,
    "DB_HOST=127.0.0.1",
    "DB_PORT=3306",
    "DB_USER=cafex_app",
    `DB_PASSWORD=${appPassword}`,
    "DB_NAME=cafex",
    `JWT_SECRET=${jwtSecret}`,
    `JWT_EXPIRES_IN=${current.JWT_EXPIRES_IN ?? "7d"}`,
    "",
  ].join("\n");

  const temporaryPath = `${envPath}.tmp`;
  await writeFile(temporaryPath, env, { encoding: "utf8", mode: 0o600 });
  await rename(temporaryPath, envPath);
}

async function main() {
  const adminPassword =
    process.env.MYSQL_ADMIN_PASSWORD ??
    (await promptForHiddenInput("MySQL password for root@localhost: "));

  if (!adminPassword) {
    throw new Error("The MySQL root password cannot be empty on this installation.");
  }

  const connection = await mysql.createConnection({
    host: "127.0.0.1",
    port: 3306,
    user: "root",
    password: adminPassword,
    multipleStatements: true,
  });

  const appPassword = randomBytes(24).toString("base64url");

  try {
    await connection.query(await readFile(schemaPath, "utf8"));
    await connection.query(await readFile(seedPath, "utf8"));
    await connection.query(
      "CREATE USER IF NOT EXISTS ?@? IDENTIFIED BY ?",
      ["cafex_app", "localhost", appPassword],
    );
    await connection.query(
      "ALTER USER ?@? IDENTIFIED BY ?",
      ["cafex_app", "localhost", appPassword],
    );
    await connection.query(
      "GRANT SELECT, INSERT, UPDATE, DELETE ON `cafex`.* TO ?@?",
      ["cafex_app", "localhost"],
    );
  } finally {
    await connection.end();
  }

  await saveAppEnvironment({ appPassword });
  console.log("CafeX database is ready and backend/.env has been configured.");
  console.log("Start the API with: npm run dev");
}

main().catch((error) => {
  if (error.code === "ER_ACCESS_DENIED_ERROR") {
    console.error("MySQL rejected that root password. Use the password for Workbench's Local instance 3306 connection.");
  } else if (error.code === "ECONNREFUSED") {
    console.error("MySQL is not running on 127.0.0.1:3306. Start the MySQL server, then run this command again.");
  } else {
    console.error(error.message);
  }
  process.exitCode = 1;
});
