const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:4000/api";

export const FALLBACK_MENU = [
  {
    id: 1,
    name: "Himalayan Honey Latte",
    description: "Double espresso, steamed milk and wild Himalayan honey.",
    price: 280,
    imageUrl: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=900&q=85",
    badge: "CafeX favorite",
    prepMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    category: "Coffee",
    categorySlug: "coffee",
  },
  {
    id: 2,
    name: "Classic Cappuccino",
    description: "Silky microfoam over rich espresso with a cocoa finish.",
    price: 220,
    imageUrl: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 7,
    isAvailable: true,
    isFeatured: true,
    category: "Coffee",
    categorySlug: "coffee",
  },
  {
    id: 3,
    name: "Caramel Cold Brew",
    description: "Slow-steeped coffee, caramel cream and a touch of sea salt.",
    price: 260,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=85",
    badge: "Cold",
    prepMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    category: "Cold Drinks",
    categorySlug: "cold-drinks",
  },
  {
    id: 4,
    name: "Masala Chiya",
    description: "Nepali milk tea brewed with cardamom, ginger and warm spices.",
    price: 120,
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=85",
    badge: "Local",
    prepMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    category: "Tea",
    categorySlug: "tea",
  },
  {
    id: 5,
    name: "Butter Croissant",
    description: "Flaky, golden layers baked fresh every morning.",
    price: 180,
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85",
    badge: "Fresh baked",
    prepMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    category: "Bakery",
    categorySlug: "bakery",
  },
  {
    id: 6,
    name: "Avocado Toast",
    description: "Sourdough, smashed avocado, tomatoes, herbs and soft egg.",
    price: 360,
    imageUrl: "/avocado-toast.jpg",
    badge: "Brunch",
    prepMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    category: "Breakfast",
    categorySlug: "breakfast",
  },
  {
    id: 7,
    name: "Kathmandu Mocha",
    description: "Espresso, dark chocolate and steamed milk with a cocoa dusting.",
    price: 290,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85",
    badge: "Chocolate",
    prepMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    category: "Coffee",
    categorySlug: "coffee",
  },
  {
    id: 8,
    name: "Velvet Flat White",
    description: "A smooth double ristretto finished with a thin layer of microfoam.",
    price: 240,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 7,
    isAvailable: true,
    isFeatured: false,
    category: "Coffee",
    categorySlug: "coffee",
  },
  {
    id: 9,
    name: "Cafe Americano",
    description: "Fresh espresso lengthened with hot water for a clean, bold cup.",
    price: 180,
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 5,
    isAvailable: true,
    isFeatured: false,
    category: "Coffee",
    categorySlug: "coffee",
  },
  {
    id: 10,
    name: "Himalayan Black Tea",
    description: "Bright high-grown black tea with honeyed malt and floral notes.",
    price: 140,
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=85",
    badge: "Nepal grown",
    prepMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    category: "Tea",
    categorySlug: "tea",
  },
  {
    id: 11,
    name: "Lemon Ginger Tea",
    description: "Fresh ginger, lemon and honey steeped into a warming herbal cup.",
    price: 150,
    imageUrl: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=85",
    badge: "Caffeine free",
    prepMinutes: 7,
    isAvailable: true,
    isFeatured: false,
    category: "Tea",
    categorySlug: "tea",
  },
  {
    id: 12,
    name: "Matcha Latte",
    description: "Ceremonial-style matcha whisked with lightly sweetened steamed milk.",
    price: 260,
    imageUrl: "https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    category: "Tea",
    categorySlug: "tea",
  },
  {
    id: 13,
    name: "Mint Green Tea",
    description: "Delicate green tea infused with cooling garden mint.",
    price: 140,
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=85",
    badge: "Refreshing",
    prepMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    category: "Tea",
    categorySlug: "tea",
  },
  {
    id: 14,
    name: "Chocolate Croissant",
    description: "Buttery laminated pastry wrapped around rich dark chocolate.",
    price: 220,
    imageUrl: "https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    category: "Bakery",
    categorySlug: "bakery",
  },
  {
    id: 15,
    name: "Cinnamon Roll",
    description: "Soft brioche swirled with cinnamon sugar and vanilla glaze.",
    price: 210,
    imageUrl: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=900&q=85",
    badge: "Sweet",
    prepMinutes: 5,
    isAvailable: true,
    isFeatured: false,
    category: "Bakery",
    categorySlug: "bakery",
  },
  {
    id: 16,
    name: "Blueberry Muffin",
    description: "Tender vanilla muffin packed with blueberries and a crisp top.",
    price: 190,
    imageUrl: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    category: "Bakery",
    categorySlug: "bakery",
  },
  {
    id: 17,
    name: "Banana Bread",
    description: "Moist banana loaf with toasted walnuts and a hint of cinnamon.",
    price: 170,
    imageUrl: "/banana-bread.jpg",
    badge: "House baked",
    prepMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    category: "Bakery",
    categorySlug: "bakery",
  },
  {
    id: 18,
    name: "CafeX Breakfast Plate",
    description: "Eggs, toast, breakfast potatoes, greens and grilled tomato.",
    price: 480,
    imageUrl: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=85",
    badge: "Hearty",
    prepMinutes: 16,
    isAvailable: true,
    isFeatured: false,
    category: "Breakfast",
    categorySlug: "breakfast",
  },
  {
    id: 19,
    name: "Eggs Benedict",
    description: "Poached eggs and hollandaise over toasted English muffins.",
    price: 420,
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 15,
    isAvailable: true,
    isFeatured: false,
    category: "Breakfast",
    categorySlug: "breakfast",
  },
  {
    id: 20,
    name: "Pancake Stack",
    description: "Fluffy pancakes with seasonal fruit, butter and maple syrup.",
    price: 340,
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=85",
    badge: "Weekend favorite",
    prepMinutes: 14,
    isAvailable: true,
    isFeatured: false,
    category: "Breakfast",
    categorySlug: "breakfast",
  },
  {
    id: 21,
    name: "Granola Yogurt Bowl",
    description: "Creamy yogurt, house granola, fresh fruit and Himalayan honey.",
    price: 300,
    imageUrl: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=900&q=85",
    badge: "Light",
    prepMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    category: "Breakfast",
    categorySlug: "breakfast",
  },
  {
    id: 22,
    name: "Iced Americano",
    description: "Double espresso poured over cold water and ice.",
    price: 190,
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    category: "Cold Drinks",
    categorySlug: "cold-drinks",
  },
  {
    id: 23,
    name: "Mango Lassi",
    description: "Ripe mango blended with yogurt, cardamom and a touch of honey.",
    price: 250,
    imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=85",
    badge: "Seasonal",
    prepMinutes: 5,
    isAvailable: true,
    isFeatured: false,
    category: "Cold Drinks",
    categorySlug: "cold-drinks",
  },
  {
    id: 24,
    name: "Strawberry Lemonade",
    description: "Fresh strawberry, lemon and sparkling water over ice.",
    price: 220,
    imageUrl: "/strawberry-lemonade.jpg",
    badge: "Sparkling",
    prepMinutes: 5,
    isAvailable: true,
    isFeatured: false,
    category: "Cold Drinks",
    categorySlug: "cold-drinks",
  },
  {
    id: 25,
    name: "Iced Matcha",
    description: "Whisked matcha, cold milk and vanilla served over ice.",
    price: 270,
    imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=900&q=85",
    prepMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    category: "Cold Drinks",
    categorySlug: "cold-drinks",
  },
];

export async function apiRequest(path, options = {}, token) {
  const headers = new Headers(options.headers);

  if (!(options.body instanceof FormData)) {
    headers.set("Content-Type", "application/json");
  }
  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }

  const response = await fetch(`${API_URL}${path}`, { ...options, headers });
  const data = response.status === 204 ? null : await response.json();

  if (!response.ok) {
    throw new Error(data?.message ?? "Something went wrong");
  }

  return data;
}
